# Generated by Django 5.1 on 2024-09-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_dish_image_alter_dish_estimatedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
