# Generated by Django 5.1 on 2024-09-09 04:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipestep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_dish', to=settings.AUTH_USER_MODEL),
        ),
    ]
