# Generated by Django 5.1 on 2024-09-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_dish_bookmarked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
